name: Infrastructure CI/CD Pipeline

on:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "1220-IAC"
  CONFIG_DIRECTORY: "./modules/application"
  
jobs:
  Deploy_Resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem

      - name: SSH into EC2 and Deploy Container
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            echo "Stopping and removing the existing container..."
            docker stop smart_home_container || true
            docker rm smart_home_container || true

            echo "Pulling latest container from ECR..."
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
            docker pull ${{ secrets.ECR_REGISTRY }}/smart-home-controller:latest

            echo "Running the new container..."
            docker run -d --name smart_home_container -p 8080:8080 ${{ secrets.ECR_REGISTRY }}/smart-home-controller:latest

            echo "Deployment complete!"
          EOF